### ISSUE TITLE
DOC: Tip about referencing index file

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/cloud-commerce-spartacus-storefront-docs#111] opened 2019-05-06 19:42 UTC
See  https://spartacus-storefront.slack.com/archives/DCUMSPMTR/p1553760512000100

**Comment by LTiger14** [comment] 2019-07-10 19:40
This is already addressed in this file: https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/blob/develop/_pages/contributing/definition-of-done.md#verify-the-production-build-works

```
Be careful when using `index.ts` files (that is, barrel files). When running a production build, you might see the following error in the `node/webpack` console:

  ```
  ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by using 'barrel' index.ts files.
  ```

  This is usually caused by having the following import:

  ```
  import * as fromServices from '../../services'.
  ```

  Instead, you should directly import each class, as follows:

  ```import { OccCmsService } from '../../services/occ-cms.service'
  import { DefaultPageService } from '../../services/default-page.service'
  ```
```

**Comment by LTiger14** [comment] 2019-07-10 19:41
Already done

**Closed by LTiger14** 2019-07-10 19:41 UTC
